version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: cricket_analytics
      POSTGRES_USER: cricket_user
      POSTGRES_PASSWORD: cricket_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
