services:
  - type: web
    name: cricket-dashboard
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && python app.py"
    envVars:
      - key: PORT
        value: 8000